### ISSUE TITLE
Issues with lost grid

### ISSUE THREAD

**Issue by juanpasolano** [jeffjewiss/sails-hook-postcss#1]
Hi there.
First of all, thank you for sharing this hook. It will make the asset pipeline easily extensible.

I was having an issue with the lostGrid postcss process. Fortunately it was ease to fix, i just bump the postcss version from `^4.1.16` to `^5.0.10` and it went back to normal.

**Comment by jeffjewiss** [comment]
Hi Juan,

Sorry for not replying, I completely missed that you submitted an issue. I feel really bad that I didn't get to this sooner.

I've published version `1.0.2`, which bumps Postcss to version 5. I believe that should solve the issue, as you mentioned. I'm going to close this, but please let me know if upgrading to v1.0.2 doesn't fix it.

Thanks!
